In [1]:
import math as m 
from random import randint
import statistics as s
from matplotlib import pyplot as plt
import numpy as np 

In [17]:
x = np.zeros((8,8),int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [40]:
arr = np.zeros((5,5),int)
arr += np.arange(0,5)
print (arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [42]:
np.random.randint (0, 100, (3, 3,3))

array([[[21, 58, 20],
        [21, 67, 70],
        [ 8,  9, 21]],

       [[58, 18, 11],
        [ 8, 51, 61],
        [79, 32, 18]],

       [[15, 73, 61],
        [20, 19, 16],
        [76, 26, 72]]])