In [1]:
import math as m 
from random import randint
import statistics as s
from matplotlib import pyplot as plt
import numpy as np 

In [17]:
x = np.zeros((8,8),int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [40]:
arr = np.zeros((5,5),int)
arr += np.arange(0,5)
print (arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [42]:
np.random.randint (0, 100, (3, 3,3))

array([[[21, 58, 20],
        [21, 67, 70],
        [ 8,  9, 21]],

       [[58, 18, 11],
        [ 8, 51, 61],
        [79, 32, 18]],

       [[15, 73, 61],
        [20, 19, 16],
        [76, 26, 72]]])

In [1]:
import numpy as np

arr = np.ones((5,5),int)
arr[1:-1,1:-1] = 0
print (arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
import numpy as np 

np.sort(np.random.randint(0,100,10))

In [59]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/akmand/datasets/main/adult.csv"
dataframe = pd.read_csv(url)
dataframe.head(100)
dataframe.tail(3)
dataframe.shape
dataframe.describe()


age  education_num  hours_per_week       capital
count  45222.000000   45222.000000    45222.000000  45222.000000
mean      38.547941      10.118460       40.938017   1012.834925
std       13.217870       2.552881       12.007508   7530.315380
min       17.000000       1.000000        1.000000  -4356.000000
25%       28.000000       9.000000       40.000000      0.000000
50%       37.000000      10.000000       40.000000      0.000000
75%       47.000000      13.000000       45.000000      0.000000
max       90.000000      16.000000       99.000000  99999.000000

In [24]:
dataframe.head(100)

age         workclass  education_num      marital_status  \
0    39         State-gov             13       Never-married   
1    50  Self-emp-not-inc             13  Married-civ-spouse   
2    38           Private              9            Divorced   
3    53           Private              7  Married-civ-spouse   
4    28           Private             13  Married-civ-spouse   
..  ...               ...            ...                 ...   
95   20           Private             10       Never-married   
96   29           Private              9       Never-married   
97   32      Self-emp-inc              9  Married-civ-spouse   
98   30           Private              7       Never-married   
99   31         Local-gov              9       Never-married   

           occupation   relationship   race  gender  hours_per_week  \
0        Adm-clerical  Not-in-family  White    Male              40   
1     Exec-managerial        Husband  White    Male              13   
2   Handlers-cleaners  Not-in-family  White    Male              40   
3   Handlers-cleaners        Husband  Other    Male              40   
4      Prof-specialty           Wife  Other  Female              40   
..                ...            ...    ...     ...             ...   
95       Tech-support      Own-child  White  Female              40   
96       Craft-repair  Not-in-family  White    Male              40   
97       Craft-repair        Husband  White    Male              40   
98  Handlers-cleaners      Own-child  White    Male              40   
99       Adm-clerical  Not-in-family  White  Female              40   

   native_country  capital income_status  
0   United-States     2174         <=50K  
1   United-States        0         <=50K  
2   United-States        0         <=50K  
3   United-States        0         <=50K  
4           Other        0         <=50K  
..            ...      ...           ...  
95  United-States        0         <=50K  
96  United-States        0         <=50K  
97  United-States     7688          >50K  
98  United-States        0         <=50K  
99  United-States        0         <=50K  

[100 rows x 12 columns]

In [23]:
dataframe[dataframe['education_num'] == 13].head(100)

age         workclass  education_num      marital_status  \
0     39         State-gov             13       Never-married   
1     50  Self-emp-not-inc             13  Married-civ-spouse   
4     28           Private             13  Married-civ-spouse   
9     42           Private             13  Married-civ-spouse   
11    30         State-gov             13  Married-civ-spouse   
..   ...               ...            ...                 ...   
568   52      Self-emp-inc             13  Married-civ-spouse   
570   23           Private             13       Never-married   
579   49           Private             13  Married-civ-spouse   
583   30           Private             13  Married-civ-spouse   
586   21           Private             13       Never-married   

            occupation   relationship   race  gender  hours_per_week  \
0         Adm-clerical  Not-in-family  White    Male              40   
1      Exec-managerial        Husband  White    Male              13   
4       Prof-specialty           Wife  Other  Female              40   
9      Exec-managerial        Husband  White    Male              40   
11      Prof-specialty        Husband  Other    Male              40   
..                 ...            ...    ...     ...             ...   
568              Sales        Husband  White    Male              55   
570              Sales      Own-child  White  Female              20   
579              Sales        Husband  White    Male              26   
583       Adm-clerical           Wife  Other  Female              40   
586  Handlers-cleaners  Not-in-family  White    Male              40   

    native_country  capital income_status  
0    United-States     2174         <=50K  
1    United-States        0         <=50K  
4            Other        0         <=50K  
9    United-States     5178          >50K  
11           Other        0          >50K  
..             ...      ...           ...  
568  United-States        0         <=50K  
570  United-States        0         <=50K  
579  United-States        0          >50K  
583  United-States        0          >50K  
586  United-States        0         <=50K  

[100 rows x 12 columns]

In [26]:
from sklearn import preprocessing as p


In [72]:
url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
dataframe = pd.read_csv(url)
dataframe.head(100)


sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0               5.1             3.5              1.4             0.2   
1               4.9             3.0              1.4             0.2   
2               4.7             3.2              1.3             0.2   
3               4.6             3.1              1.5             0.2   
4               5.0             3.6              1.4             0.2   
..              ...             ...              ...             ...   
95              5.7             3.0              4.2             1.2   
96              5.7             2.9              4.2             1.3   
97              6.2             2.9              4.3             1.3   
98              5.1             2.5              3.0             1.1   
99              5.7             2.8              4.1             1.3   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
95  versicolor  
96  versicolor  
97  versicolor  
98  versicolor  
99  versicolor  

[100 rows x 5 columns]

In [111]:
ggg = np.array(dataframe["sepal_length_cm"])
result = p.normalize([ggg])
print(result)

[[0.07056264 0.06779548 0.06502832 0.06364474 0.06917906 0.07471338
  0.06364474 0.06917906 0.06087757 0.06779548 0.07471338 0.0664119
  0.0664119  0.05949399 0.08024771 0.07886413 0.07471338 0.07056264
  0.07886413 0.07056264 0.07471338 0.07056264 0.06364474 0.07056264
  0.0664119  0.06917906 0.06917906 0.07194622 0.07194622 0.06502832
  0.0664119  0.07471338 0.07194622 0.07609697 0.06779548 0.06917906
  0.07609697 0.06779548 0.06087757 0.07056264 0.06917906 0.06226115
  0.06087757 0.06917906 0.07056264 0.0664119  0.07056264 0.06364474
  0.0733298  0.06917906 0.09685068 0.0885492  0.0954671  0.07609697
  0.08993278 0.07886413 0.08716562 0.06779548 0.09131636 0.07194622
  0.06917906 0.08163129 0.08301487 0.08439845 0.07748055 0.09269994
  0.07748055 0.08024771 0.08578203 0.07748055 0.08163129 0.08439845
  0.08716562 0.08439845 0.0885492  0.09131636 0.09408352 0.09269994
  0.08301487 0.07886413 0.07609697 0.07609697 0.08024771 0.08301487
  0.07471338 0.08301487 0.09269994 0.08716562 0.0

In [1]:
print(2)


1
